CREATE TABLE AREA (
    ID_AREA BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE CONTRATO (
    CODIGO_CONTRATO VARCHAR(100) PRIMARY KEY,
    ID_AREA BIGINT,
    FOREIGN KEY (ID_AREA) REFERENCES AREA(ID_AREA)
);

CREATE TABLE ORDEM_SERVICO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CONTRATO VARCHAR(100),
    NUMERO_OS VARCHAR(100) NOT NULL,
    FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO(CODIGO_CONTRATO)
);

CREATE TABLE RECURSO (
    ID_RECURSO BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CONTRATO VARCHAR(100),
    NOME VARCHAR(255) NOT NULL,
    FATOR_AJUSTE BIGINT,
    FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO(CODIGO_CONTRATO)
);

CREATE TABLE CONTRATO_DETALHE (
    ID_CONTRATO_DETALHE BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CONTRATO VARCHAR(100),
    PREPOSTO VARCHAR(255),
    FISCAL VARCHAR(255),
    GESTOR VARCHAR(255),
    OBJETO VARCHAR(255),
    PROCESSO_SEI VARCHAR(255),
    FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO(CODIGO_CONTRATO)
);

CREATE TABLE FATURAMENTO (
    ID_FATURAMENTO BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CONTRATO VARCHAR(100),
    OBJETIVO VARCHAR(255),
    VALOR DECIMAL(19,2),
    NUMERO_MEDICAO VARCHAR(100),
    FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATO(CODIGO_CONTRATO)
);

CREATE TABLE FATURAMENTO_DETALHE (
    ID_FATURAMENTO_DETALHE BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_FATURAMENTO BIGINT,
    DESCRICAO VARCHAR(255),
    FOREIGN KEY (ID_FATURAMENTO) REFERENCES FATURAMENTO(ID_FATURAMENTO)
);

CREATE TABLE FERIADO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DATA DATE NOT NULL
); 